# TEMPORARY input files
bam_files = {'venter_short': '/home/jgarthur/sv/analysis/alignments/bwa_mem/short-reads/jun_jul.mdup.merge.mdup.qnamesorted.matedata.sorted.bam',
             'venter_1rg': '/home/jgarthur/sv/analysis/alignments/bwa_mem/short-reads/jun_jul.mdup.merge.mdup.1rg.qnamesorted.matedata.sorted.bam',
             'example': '/scratch/PI/whwong/svproject/example/reads.bam',
             'small': '/scratch/PI/whwong/svproject/example_small/reads.bam',
             'varsim': '/home/jgarthur/sv/simdata/varsim-40x-HiSeq2k/alignments/bwa_mem/merged.matedata.bam',
             'hepg2_short': '/home/jgarthur/sv/encode-cancer-data/HepG2 deep WGS/hepg2_alignments.bam',
             'k562_short': '/home/jgarthur/sv/encode-cancer-data/K562 deep WGS/k562_alignments.bam',
             'na12878': '/scratch/PI/whwong/svproject/na12878-data/platinum-genomes/ERR194147.matetags.sorted.mdup.bam',
             'fib1': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/fib1.recal.sorted.bam',
             'fib2': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/fib2.recal.sorted.bam',
             'fib3': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/fib3.recal.sorted.bam',
             'fib4': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/fib4.recal.sorted.bam',
             'fib5': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/fib5.recal.sorted.bam',
             'fib6': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/fib6.recal.sorted.bam',
             'pos1': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/pos1.recal.sorted.bam',
             'pos2': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/pos2.recal.sorted.bam',
             'pos3': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/pos3.recal.sorted.bam',
             'pos4': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/pos4.recal.sorted.bam',
             'pos5': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/pos5.recal.sorted.bam',
             'pos6': '/scratch/PI/whwong/svproject/data2/urban-somatic-data/pos6.recal.sorted.bam'}
meta_files = {'venter_short': '/home/jgarthur/sv/meta/short.txt',
              'venter_1rg': '/home/jgarthur/sv/meta/short-1rg.txt',
              'example': '/scratch/PI/whwong/svproject/example/meta.txt',
              'small': '/scratch/PI/whwong/svproject/example_small/meta.txt',
              'varsim': '/home/jgarthur/sv/meta/varsim.txt',
              'hepg2_short': '/home/jgarthur/sv/meta/HepG2-short.txt',
              'k562_short': '/home/jgarthur/sv/meta/K562-short.txt',
              'na12878': '/home/jgarthur/sv/meta/na12878.txt',
              'fib1': '/home/jgarthur/sv/meta/urban-fib.txt',
              'fib2': '/home/jgarthur/sv/meta/urban-fib.txt',
              'fib3': '/home/jgarthur/sv/meta/urban-fib.txt',
              'fib4': '/home/jgarthur/sv/meta/urban-fib.txt',
              'fib5': '/home/jgarthur/sv/meta/urban-fib.txt',
              'fib6': '/home/jgarthur/sv/meta/urban-fib.txt',
              'pos1': '/home/jgarthur/sv/meta/urban-pos.txt',
              'pos2': '/home/jgarthur/sv/meta/urban-pos.txt',
              'pos3': '/home/jgarthur/sv/meta/urban-pos.txt',
              'pos4': '/home/jgarthur/sv/meta/urban-pos.txt',
              'pos5': '/home/jgarthur/sv/meta/urban-pos.txt',
              'pos6': '/home/jgarthur/sv/meta/urban-pos.txt'}
# BEFORE SUBMIT change
outdirs = {'venter_short': '/home/jgarthur/sv/parser-out/{name}/',
           'venter_1rg': '/home/jgarthur/sv/parser-out/{name}/',
           'example': '/home/jgarthur/sv/example/{name}/',
           'small': '/home/jgarthur/sv/example_small/{name}/',
           'varsim': '/home/jgarthur/sv/parser-out/{name}/',
           'hepg2_short': '/home/jgarthur/sv/encode-cancer-analysis/{name}/',
           'k562_short': '/home/jgarthur/sv/encode-cancer-analysis/{name}/',
           'na12878': '/home/jgarthur/sv/parser-out/{name}/'}
