##### UNUSED #####
jul_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/short-reads/jul_2.mdup.bam'
jun_jul_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/short-reads/jun_jul.mdup.merge.mdup.realn.recal.bam'
jun_jul_norealn_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/short-reads/jun_jul.mdup.merge.mdup.bam'
jun_jul_matedata_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/short-reads/jun_jul.mdup.merge.mdup.qnamesorted.matedata.sorted.bam'
mp_2k_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-2k-merged/mp-2k.MP-UN.mdup.PE.mdup.merge.realn.recal.bam'
mp_2k_norealn_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-2k-merged/mp-2k.MP-UN.mdup.PE.mdup.merge.bam'
mp_2k_matedata_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-2k-merged/mp-2k.MP-UN.mdup.PE.mdup.merge.qnamesorted.matedata.sorted.bam'
mp_5k_bam='/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-5k-jul20/mp-5k.MP-UN-PE.merge.mdup.realn.bam'
mp_5k_norealn_bam='/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-5k-jul20/mp-5k.MP-UN-PE.merge.mdup.bam'
mp_5k_matedata_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-5k-jul20/mp-5k.MP-UN-PE.merge.mdup.matedata.sorted.bam'
mp_10k_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-10k-merged/mp-10k.MP-UN.mdup.PE.mdup.merge.realn.recal.bam'
mp_10k_norealn_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-10k-merged/mp-10k.MP-UN.mdup.PE.mdup.merge.bam'
mp_10k_matedata_bam = '/home/jgarthur/sv/analysis/alignments/bwa_mem/mp-10k-merged/mp-10k.MP-UN.mdup.PE.mdup.merge.qnamesorted.matedata.sorted.bam'
varsim_bam = '/home/jgarthur/sv/simdata/varsim-40x-HiSeq2k/alignments/bwa_mem/merged.matedata.bam'

jun_jul_meta = '/home/jgarthur/sv/meta/short.txt'
mp_2k_meta = '/home/jgarthur/sv/meta/mp-2k.txt'
mp_5k_meta = '/home/jgarthur/sv/meta/mp-5k.txt'
mp_10k_meta = '/home/jgarthur/sv/meta/mp-10k.txt'
varsim_meta = '/home/jgarthur/sv/meta/varsim.txt'

hepg2_short_bam = '/home/jgarthur/sv/encode-cancer-data/HepG2 deep WGS/hepg2_alignments.bam'
hepg2_short_meta = '/home/jgarthur/sv/meta/HepG2-short.txt'
hepg2_3k_bam = '/home/jgarthur/sv/encode-cancer-data/HepG2-mp-3k/alignments/HepG2-3kb-MP-UN-PE.mdup.MP.bam'
hepg2_3k_meta = '/home/jgarthur/sv/meta/HepG2-MP.txt'

k562_short_bam = '/home/jgarthur/sv/encode-cancer-data/K562 deep WGS/k562_alignments.bam'
k562_short_meta = '/home/jgarthur/sv/meta/K562-short.txt'
k562_3k_bam = '/home/jgarthur/sv/encode-cancer-data/K562-mp-3k/alignments/K562-3kb-MP-UN-PE.mdup.MP.bam'
k562_3k_meta = '/home/jgarthur/sv/meta/K562-MP.txt'
